
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.VBox vbox3;
	private global::Gtk.RadioButton installedfontsradiobutton;
	private global::Gtk.RadioButton fromfileradiobutton;
	private global::Gtk.Label GtkLabel2;
	private global::Gtk.Frame installedfontsframe;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.FontButton fontbutton;
	private global::Gtk.Label GtkLabel5;
	private global::Gtk.Frame fromfileframe;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.FileChooserButton fontfilechooserbutton;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label sizelabel;
	private global::Gtk.SpinButton sizespinbutton;
	private global::Gtk.Label GtkLabel7;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox4;
	private global::Gtk.CheckButton Antialiasingcheckbutton;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label label2;
	private global::Gtk.SpinButton spinbutton1;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label3;
	private global::Gtk.SpinButton spinbutton2;
	private global::Gtk.CheckButton checkbutton2;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label5;
	private global::Gtk.CheckButton transparentbackgroundcheckbutton;
	private global::Gtk.ColorButton backgroundcolorbutton;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label4;
	private global::Gtk.ColorButton fontcolorbutton;
	private global::Gtk.Label GtkLabel10;
	private global::Gtk.Frame frame5;
	private global::Gtk.Alignment GtkAlignment8;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Image previewimage;
	private global::Gtk.Button generatebutton;
	private global::Gtk.FileChooserButton outputfilechooserbutton;
	private global::Gtk.Label GtkLabel13;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Font Whiz");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.WidthRequest = 200;
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.installedfontsradiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Installed Fonts"));
		this.installedfontsradiobutton.CanFocus = true;
		this.installedfontsradiobutton.Name = "installedfontsradiobutton";
		this.installedfontsradiobutton.DrawIndicator = true;
		this.installedfontsradiobutton.UseUnderline = true;
		this.installedfontsradiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox3.Add (this.installedfontsradiobutton);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.installedfontsradiobutton]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fromfileradiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("From File"));
		this.fromfileradiobutton.CanFocus = true;
		this.fromfileradiobutton.Name = "fromfileradiobutton";
		this.fromfileradiobutton.DrawIndicator = true;
		this.fromfileradiobutton.UseUnderline = true;
		this.fromfileradiobutton.Group = this.installedfontsradiobutton.Group;
		this.vbox3.Add (this.fromfileradiobutton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fromfileradiobutton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.GtkAlignment3.Add (this.vbox3);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Source</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame4]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.installedfontsframe = new global::Gtk.Frame ();
		this.installedfontsframe.Name = "installedfontsframe";
		this.installedfontsframe.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child installedfontsframe.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.fontbutton = new global::Gtk.FontButton ();
		this.fontbutton.CanFocus = true;
		this.fontbutton.Name = "fontbutton";
		this.GtkAlignment1.Add (this.fontbutton);
		this.installedfontsframe.Add (this.GtkAlignment1);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Installed Fonts</b>");
		this.GtkLabel5.UseMarkup = true;
		this.installedfontsframe.LabelWidget = this.GtkLabel5;
		this.vbox1.Add (this.installedfontsframe);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.installedfontsframe]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fromfileframe = new global::Gtk.Frame ();
		this.fromfileframe.Sensitive = false;
		this.fromfileframe.Name = "fromfileframe";
		this.fromfileframe.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child fromfileframe.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.fontfilechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fontfilechooserbutton.Name = "fontfilechooserbutton";
		this.vbox5.Add (this.fontfilechooserbutton);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.fontfilechooserbutton]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.sizelabel = new global::Gtk.Label ();
		this.sizelabel.Name = "sizelabel";
		this.sizelabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Size");
		this.hbox3.Add (this.sizelabel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.sizelabel]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.sizespinbutton = new global::Gtk.SpinButton (0, 100, 1);
		this.sizespinbutton.CanFocus = true;
		this.sizespinbutton.Name = "sizespinbutton";
		this.sizespinbutton.Adjustment.PageIncrement = 10;
		this.sizespinbutton.ClimbRate = 1;
		this.sizespinbutton.Numeric = true;
		this.sizespinbutton.Value = 8;
		this.hbox3.Add (this.sizespinbutton);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.sizespinbutton]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox5.Add (this.hbox3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox3]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.GtkAlignment2.Add (this.vbox5);
		this.fromfileframe.Add (this.GtkAlignment2);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>From File</b>");
		this.GtkLabel7.UseMarkup = true;
		this.fromfileframe.LabelWidget = this.GtkLabel7;
		this.vbox1.Add (this.fromfileframe);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fromfileframe]));
		w15.Position = 2;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w16.Position = 0;
		w16.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.Antialiasingcheckbutton = new global::Gtk.CheckButton ();
		this.Antialiasingcheckbutton.CanFocus = true;
		this.Antialiasingcheckbutton.Name = "Antialiasingcheckbutton";
		this.Antialiasingcheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Anti-aliasing");
		this.Antialiasingcheckbutton.DrawIndicator = true;
		this.Antialiasingcheckbutton.UseUnderline = true;
		this.vbox4.Add (this.Antialiasingcheckbutton);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.Antialiasingcheckbutton]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
		this.hbox4.Add (this.label2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinbutton1 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.spinbutton1.Adjustment.PageIncrement = 10;
		this.spinbutton1.ClimbRate = 1;
		this.spinbutton1.Numeric = true;
		this.hbox4.Add (this.spinbutton1);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.spinbutton1]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.spinbutton2 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton2.CanFocus = true;
		this.spinbutton2.Name = "spinbutton2";
		this.spinbutton2.Adjustment.PageIncrement = 10;
		this.spinbutton2.ClimbRate = 1;
		this.spinbutton2.Numeric = true;
		this.hbox5.Add (this.spinbutton2);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.spinbutton2]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		this.vbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox5]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.checkbutton2 = new global::Gtk.CheckButton ();
		this.checkbutton2.CanFocus = true;
		this.checkbutton2.Name = "checkbutton2";
		this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Packing (creates .txt file)");
		this.checkbutton2.Active = true;
		this.checkbutton2.DrawIndicator = true;
		this.checkbutton2.UseUnderline = true;
		this.vbox4.Add (this.checkbutton2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.checkbutton2]));
		w24.PackType = ((global::Gtk.PackType)(1));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Background Colour:");
		this.hbox6.Add (this.label5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label5]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.transparentbackgroundcheckbutton = new global::Gtk.CheckButton ();
		this.transparentbackgroundcheckbutton.CanFocus = true;
		this.transparentbackgroundcheckbutton.Name = "transparentbackgroundcheckbutton";
		this.transparentbackgroundcheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Transparent");
		this.transparentbackgroundcheckbutton.Active = true;
		this.transparentbackgroundcheckbutton.DrawIndicator = true;
		this.transparentbackgroundcheckbutton.UseUnderline = true;
		this.hbox6.Add (this.transparentbackgroundcheckbutton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.transparentbackgroundcheckbutton]));
		w26.Position = 1;
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.backgroundcolorbutton = new global::Gtk.ColorButton ();
		this.backgroundcolorbutton.Sensitive = false;
		this.backgroundcolorbutton.CanFocus = true;
		this.backgroundcolorbutton.Events = ((global::Gdk.EventMask)(784));
		this.backgroundcolorbutton.Name = "backgroundcolorbutton";
		this.hbox6.Add (this.backgroundcolorbutton);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.backgroundcolorbutton]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.vbox4.Add (this.hbox6);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox6]));
		w28.PackType = ((global::Gtk.PackType)(1));
		w28.Position = 4;
		w28.Expand = false;
		w28.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Font Colour:");
		this.hbox2.Add (this.label4);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.fontcolorbutton = new global::Gtk.ColorButton ();
		this.fontcolorbutton.CanFocus = true;
		this.fontcolorbutton.Events = ((global::Gdk.EventMask)(784));
		this.fontcolorbutton.Name = "fontcolorbutton";
		this.hbox2.Add (this.fontcolorbutton);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.fontcolorbutton]));
		w30.Position = 1;
		w30.Expand = false;
		w30.Fill = false;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w31.PackType = ((global::Gtk.PackType)(1));
		w31.Position = 5;
		w31.Expand = false;
		w31.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel10 = new global::Gtk.Label ();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>General</b>");
		this.GtkLabel10.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel10;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(2));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment8.Name = "GtkAlignment8";
		this.GtkAlignment8.LeftPadding = ((uint)(12));
		// Container child GtkAlignment8.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.previewimage = new global::Gtk.Image ();
		this.previewimage.Name = "previewimage";
		this.vbox6.Add (this.previewimage);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.previewimage]));
		w35.Position = 0;
		// Container child vbox6.Gtk.Box+BoxChild
		this.generatebutton = new global::Gtk.Button ();
		this.generatebutton.CanFocus = true;
		this.generatebutton.Name = "generatebutton";
		this.generatebutton.UseUnderline = true;
		this.generatebutton.Label = global::Mono.Unix.Catalog.GetString ("Generate");
		this.vbox6.Add (this.generatebutton);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.generatebutton]));
		w36.PackType = ((global::Gtk.PackType)(1));
		w36.Position = 1;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.outputfilechooserbutton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.outputfilechooserbutton.Name = "outputfilechooserbutton";
		this.vbox6.Add (this.outputfilechooserbutton);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.outputfilechooserbutton]));
		w37.PackType = ((global::Gtk.PackType)(1));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.GtkAlignment8.Add (this.vbox6);
		this.frame5.Add (this.GtkAlignment8);
		this.GtkLabel13 = new global::Gtk.Label ();
		this.GtkLabel13.Name = "GtkLabel13";
		this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Output</b>");
		this.GtkLabel13.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel13;
		this.vbox2.Add (this.frame5);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame5]));
		w40.PackType = ((global::Gtk.PackType)(1));
		w40.Position = 1;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w41.Position = 1;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 826;
		this.DefaultHeight = 523;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
